/**
 * Static promo data sourced from official minimarket websites
 * Last updated: Mei 2026
 */

export const GERAI_WEBSITES = {
  "INDOMARET": {
    official: "https://www.indomaret.co.id",
    promo:    "https://www.indomaret.co.id/katalog/super-hemat/",
    app:      null,
    label:    "indomaret.co.id",
  },
  "ALFAMART": {
    official: "https://www.alfamart.co.id",
    promo:    "https://www.alfamart.co.id/promo/hot-promo",
    app:      null,
    label:    "alfamart.co.id",
  },
  "YOMART": {
    official: "https://yomart.co.id",
    promo:    null,
    app:      null,
    label:    "yomart.co.id",
  },
  "LAWSON": {
    official: "https://lawson-indonesia.com/",
    promo:    "https://lawson-indonesia.com/promo",
    app:      null,
    label:    "lawsonindonesia.com",
  },
  "CIRCLE K": {
    official: "https://www.circlekindo.com/",
    promo:    "https://www.circlekindo.com/update-promo-circle-k-2/",
    app:      null,
    label:    "circlek.co.id",
  },
};

// Badge type → color
export const BADGE_COLORS = {
  weekend:  { bg:"#fef3c7", color:"#d97706", label:"Weekend" },
  weekly:   { bg:"#dbeafe", color:"#2563eb", label:"Mingguan" },
  member:   { bg:"#ede9fe", color:"#7c3aed", label:"Member"   },
  digital:  { bg:"#dcfce7", color:"#16a34a", label:"Digital"  },
  special:  { bg:"#fee2e2", color:"#dc2626", label:"Spesial"  },
  daily:    { bg:"#f0f9ff", color:"#0891b2", label:"Harian"   },
  app:      { bg:"#fdf4ff", color:"#a21caf", label:"App Only" },
};

export const PROMOS = {
  "INDOMARET": {
    tagline_id: "Belanja Hemat, Mudah, dan Menyenangkan",
    tagline_en: "Smart Shopping, Easy and Fun",
    promos: [
      {
        id: "indo-jsm",
        type: "weekend",
        title_id: "Promo JSM (Jumat–Sabtu–Minggu)",
        title_en: "JSM Promo (Fri–Sat–Sun)",
        period_id: "Berlaku setiap akhir pekan",
        period_en: "Every weekend",
        desc_id: "Diskon hingga 40% untuk produk sembako, minyak goreng, mie instan, minuman, snack, sabun, dan perawatan diri. Berlaku di seluruh gerai Indomaret (kecuali Indomaret Point).",
        desc_en: "Up to 40% off on staples, cooking oil, instant noodles, drinks, snacks, soap, and personal care. Valid at all Indomaret outlets (except Indomaret Point).",
        highlight: "Diskon s/d 40%",
        items_id: ["Indomie Goreng 3pcs Rp10.500", "Frisian Flag Kental Manis Rp14.700", "Indomaret Tissue B1G1 Rp11.500", "Good Day Kopi 3in1 10x20g Rp14.500"],
        items_en: ["Indomie Goreng 3pcs Rp10,500", "Frisian Flag Condensed Milk Rp14,700", "Indomaret Tissue B1G1 Rp11,500", "Good Day Coffee 3in1 10x20g Rp14,500"],
      },
      {
        id: "indo-superhemat",
        type: "weekly",
        title_id: "Super Hemat Mingguan",
        title_en: "Weekly Super Savings",
        period_id: "7–13 Mei 2026",
        period_en: "May 7–13, 2026",
        desc_id: "Promo dua mingguan dengan penawaran harga heboh untuk berbagai kategori produk. Tersedia Promo Harga Heboh, Tebus Murah, dan Hemat Banget.",
        desc_en: "Bi-weekly promo with incredible prices across product categories. Includes Harga Heboh, Tebus Murah, and Hemat Banget deals.",
        highlight: "Multi-kategori",
        items_id: ["Kapal Api Kopi Bubuk Rp16.000", "Sedaap Mie Goreng Rp8.300", "Roma Biskuit Kelapa 174g Rp11.900", "Chitato Snack 115g Rp14.900"],
        items_en: ["Kapal Api Ground Coffee Rp16,000", "Sedaap Fried Noodles Rp8,300", "Roma Coconut Biscuit 174g Rp11,900", "Chitato Snack 115g Rp14,900"],
      },
      {
        id: "indo-member",
        type: "member",
        title_id: "Promo Member Klik Indomaret",
        title_en: "Klik Indomaret Member Promo",
        period_id: "Berlaku setiap hari",
        period_en: "Valid every day",
        desc_id: "Harga eksklusif untuk member Klik Indomaret. Cashback tambahan saat bayar dengan dompet digital (DANA, OVO, GoPay). Poin reward bisa ditukar hadiah.",
        desc_en: "Exclusive prices for Klik Indomaret members. Extra cashback when paying with digital wallets. Reward points redeemable for prizes.",
        highlight: "Cashback Ekstra",
        items_id: ["Point Coffee Aren Latte 210ml Rp5.900 (beli 2)", "Cimory Fresh Milk 225ml Rp6.500", "Baby Happy Diapers L20 Rp35.900"],
        items_en: ["Point Coffee Aren Latte 210ml Rp5,900 (buy 2)", "Cimory Fresh Milk 225ml Rp6,500", "Baby Happy Diapers L20 Rp35,900"],
      },
      {
        id: "indo-susu",
        type: "special",
        title_id: "Promo Produk Susu & Bayi",
        title_en: "Baby & Dairy Product Promo",
        period_id: "8–10 Mei 2026",
        period_en: "May 8–10, 2026",
        desc_id: "Diskon hingga 30% untuk berbagai produk susu anak dan perlengkapan bayi dari brand ternama seperti Dancow, SGM, Bebelac, Chil-Kid, dan Sweety.",
        desc_en: "Up to 30% off on baby milk and infant products from top brands including Dancow, SGM, Bebelac, Chil-Kid, and Sweety.",
        highlight: "s/d 30% OFF",
        items_id: ["Chil-Kid Rp156.500", "Bebelac Rp167.900", "SGM Rp75.900", "Sweety Diapers Rp60.900", "Dancow Rp75.900"],
        items_en: ["Chil-Kid Rp156,500", "Bebelac Rp167,900", "SGM Rp75,900", "Sweety Diapers Rp60,900", "Dancow Rp75,900"],
      },
    ],
  },

  "ALFAMART": {
    tagline_id: "Belanja Puas, Harga Pas",
    tagline_en: "Shop More, Pay Less",
    promos: [
      {
        id: "alfa-jsm",
        type: "weekend",
        title_id: "Promo JSM Alfamart",
        title_en: "Alfamart JSM Weekend Promo",
        period_id: "8–10 Mei 2026",
        period_en: "May 8–10, 2026",
        desc_id: "Diskon spesial akhir pekan untuk kebutuhan harian, perlengkapan rumah tangga, hingga produk bayi. Berlaku di seluruh gerai Alfamart dan aplikasi Alfagift. Gratis ongkir via Alfagift.",
        desc_en: "Weekend discounts on daily necessities, household products, and baby items. Valid at all Alfamart outlets and Alfagift app. Free delivery via Alfagift.",
        highlight: "Gratis Ongkir",
        items_id: ["Deterjen & Sabun Mandi Diskon Besar", "Snack & Minuman Beli 2 Gratis 1", "Produk Bayi Harga Spesial"],
        items_en: ["Big Discount on Detergent & Body Soap", "Snacks & Drinks Buy 2 Get 1", "Baby Products Special Price"],
      },
      {
        id: "alfa-psm",
        type: "weekly",
        title_id: "PSM – Produk Spesial Mingguan",
        title_en: "PSM – Weekly Special Products",
        period_id: "8–15 Mei 2026",
        period_en: "May 8–15, 2026",
        desc_id: "Program promo mingguan Alfamart setiap Senin–Minggu. Menawarkan berbagai produk kebutuhan sehari-hari dengan harga super hemat. Extra potongan harga dengan GoPay & ShopeePay.",
        desc_en: "Alfamart's weekly promo program every Monday–Sunday. Offering a wide range of daily necessity products at super affordable prices. Extra discount with GoPay & ShopeePay.",
        highlight: "Ekstra GoPay",
        items_id: ["Cooking Need – Kebutuhan Dapur", "Health & Beauty – Kecantikan", "Susu & Nutrisi Anak"],
        items_en: ["Cooking Needs", "Health & Beauty", "Children's Milk & Nutrition"],
      },
      {
        id: "alfa-alfagift",
        type: "app",
        title_id: "Alfagift – Belanja Online",
        title_en: "Alfagift – Online Shopping",
        period_id: "Berlaku setiap hari",
        period_en: "Every day",
        desc_id: "Belanja dari mana saja via aplikasi Alfagift. Gratis ongkir tanpa batas, layanan siap antar ke rumah. Kumpulkan poin Ponta dan tukarkan dengan diskon belanjaan.",
        desc_en: "Shop from anywhere via Alfagift app. Unlimited free delivery to your door. Earn Ponta points and redeem for shopping discounts.",
        highlight: "Gratis Ongkir ∞",
        items_id: ["Gratis Ongkir tanpa minimal belanja", "Poin Ponta setiap transaksi", "Cashback GoPay untuk pengguna baru"],
        items_en: ["Free delivery with no minimum order", "Ponta Points every transaction", "GoPay cashback for new users"],
      },
      {
        id: "alfa-paling-murah",
        type: "special",
        title_id: "Paling Murah Sejagat",
        title_en: "Best Price Guarantee",
        period_id: "1–15 Mei 2026",
        period_en: "May 1–15, 2026",
        desc_id: "Program harga terbaik Alfamart dua mingguan dengan fokus pada produk sembako dan kebutuhan dapur. Harga dijamin paling murah untuk produk pilihan.",
        desc_en: "Alfamart's bi-weekly best price program focusing on staples and kitchen necessities. Prices guaranteed lowest for selected products.",
        highlight: "Harga Terbaik",
        items_id: ["Beras, Minyak, Gula Harga Murah", "Sabun & Deterjen Diskon", "Mie Instan Berbagai Merek"],
        items_en: ["Rice, Oil, Sugar – Best Price", "Soap & Detergent Discount", "Instant Noodles All Brands"],
      },
    ],
  },

  "YOMART": {
    tagline_id: "Belanja Hemat, Produk Lokal Berkualitas",
    tagline_en: "Save More, Quality Local Products",
    promos: [
      {
        id: "yomart-mingguan",
        type: "weekly",
        title_id: "Promo Mingguan Yomart",
        title_en: "Yomart Weekly Promo",
        period_id: "Berlaku setiap pekan",
        period_en: "Every week",
        desc_id: "Diskon rutin produk kebutuhan sehari-hari dengan penekanan pada produk lokal Jawa Barat yang berkualitas. Harga bersaing untuk kebutuhan pokok keluarga.",
        desc_en: "Regular weekly discounts on daily necessities with emphasis on quality West Java local products. Competitive prices for family staples.",
        highlight: "Produk Lokal",
        items_id: ["Kebutuhan Dapur Harga Hemat", "Produk Lokal Jawa Barat", "Minuman Segar & Snack"],
        items_en: ["Kitchen Essentials Bargain Price", "West Java Local Products", "Fresh Drinks & Snacks"],
      },
      {
        id: "yomart-komunitas",
        type: "member",
        title_id: "Program Komunitas Yomart",
        title_en: "Yomart Community Program",
        period_id: "Berlaku setiap hari",
        period_en: "Every day",
        desc_id: "Program loyalitas Yomart untuk warga Bandung dan sekitarnya. Harga spesial untuk produk lokal pilihan dan reward bagi pelanggan setia.",
        desc_en: "Yomart loyalty program for Bandung residents. Special prices on selected local products and rewards for loyal customers.",
        highlight: "Reward Lokal",
        items_id: ["Harga Spesial Produk Lokal", "Reward Pelanggan Setia", "Promo Komunitas Warga"],
        items_en: ["Special Price Local Products", "Loyal Customer Rewards", "Community Member Promo"],
      },
      {
        id: "yomart-akhirpekan",
        type: "weekend",
        title_id: "Promo Akhir Pekan Yomart",
        title_en: "Yomart Weekend Promo",
        period_id: "Sabtu & Minggu",
        period_en: "Saturday & Sunday",
        desc_id: "Penawaran spesial akhir pekan untuk produk segar, minuman, dan kebutuhan dapur di seluruh gerai Yomart se-Bandung Raya.",
        desc_en: "Special weekend offers on fresh products, beverages, and kitchen needs at all Yomart outlets across Greater Bandung.",
        highlight: "Weekend Deal",
        items_id: ["Produk Segar Diskon", "Minuman & Snack Hemat", "Kebutuhan Dapur Promo"],
        items_en: ["Fresh Products Discount", "Beverages & Snack Savings", "Kitchen Essentials Promo"],
      },
    ],
  },

  "LAWSON": {
    tagline_id: "Kenyamanan Gaya Jepang di Indonesia",
    tagline_en: "Japanese-Style Convenience in Indonesia",
    promos: [
      {
        id: "lawson-rte",
        type: "daily",
        title_id: "Ready-to-Eat Harian",
        title_en: "Daily Ready-to-Eat",
        period_id: "Berlaku setiap hari",
        period_en: "Every day",
        desc_id: "Produk siap makan segar setiap hari: Onigiri, Bento, Roti Lapis, dan berbagai pilihan makanan Jepang dengan harga terjangkau. Diskon untuk produk mendekati waktu habis.",
        desc_en: "Fresh ready-to-eat products every day: Onigiri, Bento, Sandwiches, and various Japanese food options at affordable prices. Discounts on near-expiry products.",
        highlight: "Fresh Daily",
        items_id: ["Onigiri berbagai rasa", "Bento Box Lunch", "Roti Lapis & Sandwich", "Kopi Lawson Station"],
        items_en: ["Onigiri various flavors", "Bento Box Lunch", "Bread Loaf & Sandwich", "Lawson Station Coffee"],
      },
      {
        id: "lawson-minuman",
        type: "special",
        title_id: "Paket Minuman Spesial",
        title_en: "Special Drink Package",
        period_id: "Mei 2026",
        period_en: "May 2026",
        desc_id: "Promo paket minuman favorit Lawson mulai Rp27.200. Tersedia berbagai pilihan minuman panas dan dingin khas Lawson Station.",
        desc_en: "Lawson's favorite drink package starting from Rp27,200. Available in various hot and cold drinks from Lawson Station.",
        highlight: "Mulai Rp27.200",
        items_id: ["Lawson Station Coffee", "Matcha Latte", "Chocolate Drink", "Paket Minuman + Onigiri"],
        items_en: ["Lawson Station Coffee", "Matcha Latte", "Chocolate Drink", "Drink + Onigiri Package"],
      },
      {
        id: "lawson-app",
        type: "app",
        title_id: "Promo Aplikasi Lawson",
        title_en: "Lawson App Promo",
        period_id: "Berlaku setiap hari",
        period_en: "Every day",
        desc_id: "Download aplikasi Lawson Indonesia untuk akses promo eksklusif, poin reward, dan informasi produk terbaru langsung dari Lawson.",
        desc_en: "Download the Lawson Indonesia app for exclusive promos, reward points, and latest product updates directly from Lawson.",
        highlight: "Eksklusif App",
        items_id: ["Poin Reward setiap transaksi", "Promo Eksklusif App", "Notifikasi Produk Baru"],
        items_en: ["Reward Points every transaction", "Exclusive App Promos", "New Product Notifications"],
      },
    ],
  },

  "CIRCLE K": {
    tagline_id: "Tempatnya Nongkrong, 24 Jam Non-Stop",
    tagline_en: "The Go-To Hangout Spot, 24/7",
    promos: [
      {
        id: "circlek-24h",
        type: "daily",
        title_id: "Promo 24 Jam Non-Stop",
        title_en: "24/7 Non-Stop Promo",
        period_id: "Berlaku setiap hari, 24 jam",
        period_en: "Every day, 24 hours",
        desc_id: "Circle K buka 24 jam sehari, 7 hari seminggu. Nikmati promo harga spesial untuk minuman, snack, dan produk impor kapan saja tanpa batas waktu.",
        desc_en: "Circle K is open 24 hours a day, 7 days a week. Enjoy special price promos on beverages, snacks, and imported products anytime.",
        highlight: "24 Jam",
        items_id: ["Frozone / Polar Pop Minuman", "Snack & Camilan Impor", "Minuman Berenergi Diskon"],
        items_en: ["Frozone / Polar Pop Drinks", "Imported Snacks", "Energy Drinks Discount"],
      },
      {
        id: "circlek-combo",
        type: "special",
        title_id: "Combo Deal Eksklusif",
        title_en: "Exclusive Combo Deals",
        period_id: "Mei 2026",
        period_en: "May 2026",
        desc_id: "Paket combo hemat Circle K: Minuman + Snack dengan harga spesial. Tersedia berbagai pilihan produk impor berkualitas dari Amerika, Eropa, dan Asia.",
        desc_en: "Circle K's value combo packages: Drink + Snack at special prices. Available in various quality imported products from America, Europe, and Asia.",
        highlight: "Combo Hemat",
        items_id: ["Minuman + Snack Combo", "Produk Impor Amerika & Eropa", "Minuman Dingin Spesial"],
        items_en: ["Drink + Snack Combo", "USA & European Imports", "Special Cold Drinks"],
      },
      {
        id: "circlek-digital",
        type: "digital",
        title_id: "Promo Pembayaran Digital",
        title_en: "Digital Payment Promo",
        period_id: "Berlaku setiap hari",
        period_en: "Every day",
        desc_id: "Cashback dan diskon ekstra saat membayar dengan dompet digital pilihan di Circle K. Berlaku untuk semua transaksi di seluruh gerai Circle K.",
        desc_en: "Cashback and extra discount when paying with selected digital wallets at Circle K. Valid for all transactions at all Circle K outlets.",
        highlight: "Cashback Digital",
        items_id: ["Cashback GoPay & OVO", "Diskon QRIS Payment", "ShopeePay Extra Promo"],
        items_en: ["GoPay & OVO Cashback", "QRIS Payment Discount", "ShopeePay Extra Promo"],
      },
    ],
  },
};
